name: Packer Validate - Jenkins AMI

on:
  pull_request:
    branches: ["main"]

jobs:
  validate:
    name: 'Packer Validate'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 'latest'
        
      - name: Jenkins Configuration
        run: |
          touch configs/jenkins.env
          echo JENKINS_URL=https://${{ secrets.JENKINS_DOMAIN }} >> configs/jenkins.env
          echo JENKINS_USERNAME=${{ secrets.JENKINS_USERNAME }} >> configs/jenkins.env
          echo JENKINS_PASSWORD=${{ secrets.JENKINS_PASSWORD }} >> configs/jenkins.env
          echo DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }} >> configs/jenkins.env
          echo DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }} >> configs/jenkins.env
          echo GITHUB_APP_ID=${{ secrets.JENKINS_GITHUB_APP_ID }} >> configs/jenkins.env
          echo "GITHUB_APP_PRIVATE_KEY='${{ secrets.JENKINS_GITHUB_APP_PRIVATE_KEY }}'" >> configs/jenkins.env
          
          tar -czvf configs.tgz -C configs .

      - name: Packer Configuration
        run: |
          touch vars.pkrvars.hcl
          echo environment=\"${{ vars.ENVIRONMENT }}\" >> vars.pkrvars.hcl
          echo aws_profile=\"${{ secrets.AWS_PROFILE }}\" >> vars.pkrvars.hcl
          echo aws_region=\"${{ secrets.AWS_REGION }}\" >> vars.pkrvars.hcl
          echo source_ami=\"${{ secrets.SOURCE_AMI }}\" >> vars.pkrvars.hcl
          echo instance_type=\"${{ secrets.INSTANCE_TYPE }}\" >> vars.pkrvars.hcl
          echo subnet_id=\"${{ secrets.SUBNET_ID }}\" >> vars.pkrvars.hcl
          echo security_group_id=\"${{ secrets.SECURITY_GROUP_ID }}\" >> vars.pkrvars.hcl
          echo ssh_username=\"${{ secrets.SSH_USERNAME }}\" >> vars.pkrvars.hcl
          echo jenkins_domain=\"${{ secrets.JENKINS_DOMAIN }}\" >> vars.pkrvars.hcl
          echo jenkins_nginx_cert_email=\"${{ secrets.JENKINS_NGINX_CERT_EMAIL }}\" >> vars.pkrvars.hcl
        working-directory: packer
 
      - name: Packer Init
        run: "packer init ."
        working-directory: packer

      - name: Packer Format
        run: "packer fmt -check jenkins.pkr.hcl"
        working-directory: packer

      - name: Packer Validate
        run: "packer validate --var-file=vars.pkrvars.hcl jenkins.pkr.hcl"
        working-directory: packer