name: Packer Build - Jenkins AMI

on:
  push:
    branches: ["main"]

jobs:
  build:
    name: 'Packer Build'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: 'latest'

      - name: Packer Configuration
        run: |
          touch vars.pkrvars.hcl
          echo environment=\"${{ vars.ENVIRONMENT }}\" >> vars.pkrvars.hcl
          echo aws_profile=\"${{ secrets.AWS_PROFILE }}\" >> vars.pkrvars.hcl
          echo aws_region=\"${{ secrets.AWS_REGION }}\" >> vars.pkrvars.hcl
          echo source_ami=\"${{ secrets.SOURCE_AMI }}\" >> vars.pkrvars.hcl
          echo instance_type=\"${{ secrets.INSTANCE_TYPE }}\" >> vars.pkrvars.hcl
          echo subnet_id=\"${{ secrets.SUBNET_ID }}\" >> vars.pkrvars.hcl
          echo security_group_id=\"${{ secrets.SECURITY_GROUP_ID }}\" >> vars.pkrvars.hcl
          echo ssh_username=\"${{ secrets.SSH_USERNAME }}\" >> vars.pkrvars.hcl
          echo jenkins_domain=\"${{ secrets.JENKINS_DOMAIN }}\" >> vars.pkrvars.hcl
          echo jenkins_nginx_cert_email=\"${{ secrets.JENKINS_NGINX_CERT_EMAIL }}\" >> vars.pkrvars.hcl
          echo jenkins_admin_username=\"${{ secrets.JENKINS_ADMIN_USERNAME }}\" >> vars.pkrvars.hcl
          echo jenkins_admin_password=\"${{ secrets.JENKINS_ADMIN_PASSWORD }}\" >> vars.pkrvars.hcl

      - name: Packer Init
        run: "packer init jenkins.pkr.hcl"

      - name: Packer Format
        run: "packer fmt ."

      - name: Packer Validate
        run: "packer validate --var-file=vars.pkrvars.hcl jenkins.pkr.hcl"

      - name: Packer Build
        run: "packer build --var-file=vars.pkrvars.hcl jenkins.pkr.hcl"